name: todo_list
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-85.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  pdf: ^3.6.5
  path_provider: ^2.0.8
  open_file: ^3.2.1
  share_plus: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

